/** ISO 639-2/B three-letter language code → display name map.
 *  Covers codes commonly found in Sonarr/Radarr mediaInfo and ffprobe output. */
export const langNames: Record<string, string> = {
  eng: 'English',
  fre: 'French',
  fra: 'French',
  spa: 'Spanish',
  ger: 'German',
  deu: 'German',
  ita: 'Italian',
  por: 'Portuguese',
  rus: 'Russian',
  chi: 'Chinese',
  zho: 'Chinese',
  jpn: 'Japanese',
  kor: 'Korean',
  ara: 'Arabic',
  dut: 'Dutch',
  nld: 'Dutch',
  dan: 'Danish',
  fin: 'Finnish',
  nor: 'Norwegian',
  nob: 'Norwegian',
  nno: 'Norwegian',
  swe: 'Swedish',
  pol: 'Polish',
  cze: 'Czech',
  ces: 'Czech',
  hun: 'Hungarian',
  tur: 'Turkish',
  gre: 'Greek',
  ell: 'Greek',
  heb: 'Hebrew',
  hin: 'Hindi',
  tha: 'Thai',
  ind: 'Indonesian',
  may: 'Malay',
  msa: 'Malay',
  vie: 'Vietnamese',
  rum: 'Romanian',
  ron: 'Romanian',
  bul: 'Bulgarian',
  hrv: 'Croatian',
  ukr: 'Ukrainian',
  ice: 'Icelandic',
  isl: 'Icelandic',
  slo: 'Slovak',
  slk: 'Slovak',
  slv: 'Slovenian',
  est: 'Estonian',
  lit: 'Lithuanian',
  lav: 'Latvian',
  tam: 'Tamil',
  tel: 'Telugu',
  ben: 'Bengali',
  urd: 'Urdu',
  mal: 'Malayalam',
  kan: 'Kannada',
  mar: 'Marathi',
  guj: 'Gujarati',
  pan: 'Punjabi',
  srp: 'Serbian',
  bos: 'Bosnian',
  mkd: 'Macedonian',
  mac: 'Macedonian',
  alb: 'Albanian',
  sqi: 'Albanian',
  geo: 'Georgian',
  kat: 'Georgian',
  arm: 'Armenian',
  hye: 'Armenian',
  per: 'Persian',
  fas: 'Persian',
  cat: 'Catalan',
  glg: 'Galician',
  baq: 'Basque',
  eus: 'Basque',
  wel: 'Welsh',
  cym: 'Welsh',
  gle: 'Irish',
  fil: 'Filipino',
  tgl: 'Tagalog',
  mni: 'Manipuri',
  khm: 'Khmer',
  lao: 'Lao',
  mya: 'Burmese',
  bur: 'Burmese',
  mon: 'Mongolian',
  nep: 'Nepali',
  sin: 'Sinhala',
  und: 'Undetermined',
};

/** Look up a human-readable name for a language code. Falls back to uppercased code. */
export function langName(code: string): string {
  return langNames[code.toLowerCase()] ?? code.toUpperCase();
}

/** Variant for nullable codes (used in AnalyzeModal). */
export function langLabel(code: string | null): string {
  if (!code) return 'Unknown';
  return langNames[code.toLowerCase()] ?? code.toUpperCase();
}
